### ISSUE TITLE
SXIV is archived

### ISSUE THREAD

**Issue by BrunoKrugel** [javiorfo/nvim-soil#1]
Since Jan/2023 `SXIV` is archived, there is an alternative being maintained [nsxiv](https://github.com/nsxiv/nsxiv), maybe this plugin can be updated to used the nsxiv version?

**Comment by javiorfo** [comment]
Hello
Thanks for the advise.
Anyway, I have made configurable the application to open the resultant image:

```lua
require'soil'.setup{ 
    image = {
        -- This is a default implementation of using xsiv to open the resultant image
        -- Edit the string to use your preferred app to open the image
        -- Some examples:
        -- return "feh " .. img
        -- return "xdg-open " .. img
        execute_to_open = function(img) 
            return "sxiv -b " .. img
        end
    }
}
```

Have a nice day!
