### ISSUE TITLE
Soil   Image not generated it.

### ISSUE THREAD

**Issue by vimalk78** [javiorfo/nvim-soil#2]
```
  Soil   Building...
  Soil   Execution error!
  Soil   Image abc-uml.svg generated!
  Soil   Image not generated it.
```

not able to generate image. but same plantuml is able to generate image in IntelliJ PlantUML plugin

**Comment by fm39hz** [comment]
> actually, this was an openjdk issue in my machine. openjdk while running could not find `libawt_xawt.so` I reinstalled openjdk-17, and after some more tweakings, this issue was solved. I could get the class diagrams.

sorry for bump this up
could you show how is your tweak for it to work?
i have the same error and trying to reinstall openjdk made no luck

**Comment by vimalk78** [comment]
> could you show how is your tweak for it to work?

it was perhaps just setting the classpath correctly. i dont remember much actually. sorry :(
