### ISSUE TITLE
Mac compatibility

### ISSUE THREAD

**Issue by PetterAxcell** [javiorfo/nvim-soil#3]
I cannot install on mac because of nsxiv.

**Comment by PetterAxcell** [comment]
Sorry, I can installed but I can use soil command.

**Comment by javiorfo** [comment]
Hi,
If you read the README you can find this:

> Caveats
> This plugin has been developed on and for Linux following open source philosophy

My entire repo is meant to be used on Linux. If you want to use it on Mac then fork it and make the appropriate modifications.

Anyway, to use other image viewer, change the setup:
```lua
require'soil'.setup{ 
    image = {
        execute_to_open = function(img) 
            return "nsxiv -b " .. img
        end
    }
} 
```

I don't own a Mac to test this plugin but I'd bet that the **:Soil** command would work.
If **plantuml** is installed in your Mac I don't see why it wouldn't work.
Otherwise you can test it downloading the **plantuml.jar** from [Official PlantUML](https://plantuml.com/download) and set it up (also check your JVM compatibility):
```lua
require'soil'.setup{ 
    -- If you want to use Plant UML jar version instead of the install version
    puml_jar = "/path/to/plantuml.jar",
}
```

Have a nice day!

**Comment by practicalli-johnny** [comment]
Unfortunately changing the image configuration still seems to trigger a check for nsxiv from the `:Soil` command.

The lazy (AstroNvim 4) config I used was:
```lua
{
    "javiorfo/nvim-soil",
    dependencies = {
      "AstroNvim/astrocore",
      -- Optional for puml syntax highlighting:
      "javiorfo/nvim-nyctophilia",
      -- lazy = true,
      filetype = "*.pu",
      opts = {
        options = {
          g = {
            puml_jar = "/Users/username/.local/share/plantuml/current.jar",
            image = {
              darkmode = true, -- Enable or disable darkmode
              format = "png", -- Choose between png or svg

              -- This is a default implementation of using nsxiv to open the resultant image
              -- Edit the string to use your preferred app to open the image
              -- Some examples:
              -- return "feh " .. img
              -- return "xdg-open " .. img
              -- execute_to_open = function(img) return "nsxiv -b " .. img end,
              execute_to_open = function(img) return "open " .. img end,
            },
          },
        },
      },
    },
  }
```

Perhaps there is a check for nsxiv regardless of which command is configured to open the file.

**Comment by javiorfo** [comment]
> Unfortunately changing the image configuration still seems to trigger a check for nsxiv from the `:Soil` command.
> 
> The lazy (AstroNvim 4) config I used was:
> 
> ```lua
> {
>     "javiorfo/nvim-soil",
>     dependencies = {
>       "AstroNvim/astrocore",
>       -- Optional for puml syntax highlighting:
>       "javiorfo/nvim-nyctophilia",
>       -- lazy = true,
>       filetype = "*.pu",
>       opts = {
>         options = {
>           g = {
>             puml_jar = "/Users/username/.local/share/plantuml/current.jar",
>             image = {
>               darkmode = true, -- Enable or disable darkmode
>               format = "png", -- Choose between png or svg
> 
>               -- This is a default implementation of using nsxiv to open the resultant image
>               -- Edit the string to use your preferred app to open the image
>               -- Some examples:
>               -- return "feh " .. img
>               -- return "xdg-open " .. img
>               -- execute_to_open = function(img) return "nsxiv -b " .. img end,
>               execute_to_open = function(img) return ":exec !open " .. img end,
>             },
>           },
>         },
>       },
>     },
>   }
> ```
> 
> There is a check for nsxiv regardless of which command is configured to open the file. https://github.com/javiorfo/nvim-soil/blob/master/lua/soil/core.lua#L18-L21
> 
> Creating a mock `nsxiv` binary using a shell script with `!/bin/sh`, and making that file executable, e.g. `chmod a+x nsxiv`, will trick soil into thinking the `nsxiv` binary is installed and the image is generated.
> 
> Then a suitable command is required to open that image using an image viewer from the MacOSX.

Hello,
I will remove the nsxiv validation.
Thanks for the info!
